[package]
name = "tag-db"
version = "0.4.0"
edition = "2024"
authors = ["Sayed Takey Tajwar Arko <sayed.takey.tajwar@g.bracu.ac.bd>"]
repository = "https://codeberg.org/tktajwar/tag-db"
categories = ["command-line-utilities", "text-editors", "database"]

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
memmap2 = "0.9.9"
regex = "1.3.9"
rust_decimal = "1.38.0"

[lib]
name = "tag"
path = "src/lib.rs"

[[bin]]
name = "tag"
path = "src/main.rs"
