\input texinfo
@settitle Tag Manual

@copying
Copyright @copyright{} 2025 Sayed Takey Tajwar Arko.
@end copying

@titlepage
@title Tag Manual
@page
@vskip 0pt plus 1filll
@end titlepage

@contents

@node Top
@top The Tag Manual

This manual is for Tag version 0.1.

Tag is an editor independent plain text document format that uses floating point number to index its sections. Tag aims to be efficient, minimal, and predictable. Tagfiles can be used for personal note taking, academic writing, literate programming, todo lists, configuration files, documentation, and any sorted and permenantly indexed plain text data.

@insertcopying

@menu
* Introduction::                        Introduction to the core philosophy of Tags
@end menu

@node Introduction
@chapter Introduction

@node Why a new document format?
@section Why a new document format?

We already have a lot of plain text document formats and some of them are great at what they do but they all have terrible referencig system and poor scaling. Most plain text document formats use "headlines" (or "heading") as their section title and the sections are later referenced with that title. But, Searching such headline is tiresome for both computers and humans alike. One will have to search through the whole document until they find the the referenced section. This means the longer your document is, the more time it'll take for you to find your desired section.

This is terrible if you want to quickly scrape a section from your long plain text file (for example, if you want to make a todo list out of your plain text document and you want to check whether one item is done or not or if you want to read your 22nd September journal entry from 3 years ago but you have a really long list). Furthermore, there can be more than one section with the same headline title. This will create confusion. To fix these issues Tag uses something similar to Niklas Luhmann's Zettlekasten method. Tag marks each section with a permenant number (tag) and sorts the sections by tag number.

@node How Tag works
@section How Tag works

If we tag our sections with permanent floating point numbers (for example: @code{9.0}) and sort the sections based on those tags, we'll have a plain text document format that's quick to look up and since the sections are permanently tagged, we can use that to reference in other sections. The reason for choosing floating point numbers for tagging is we want to be able to insert a new tag between two old tags without having to change the value of any old tag.

For example, let's say we have four sections: @code{@@1.0, @@2.0, @@3.0, @@4.0}.

@example
@@1.0
@@2.0
@@3.0
@@4.0
@end example

And, we want to insert a new section after @code{@@1.0}. In other numbered document files we'd have to name the new section the new @code{@@2.0} and the old @code{@@2.0} would be the new @code{@@3.0}... But, if we change the already assigned tag numbers, we will would lose the purpose of referencing sections with their respective tag numbers. What we do here is tag the new section a number between @code{@@1.0} and @code{@@2.0}. @code{@@1.1} would suffice here. So, the five sections are @code{@@1.0, @@1.1, @@2.0, @@3.0, @@4.0}. @code{@@1.1} is between @code{@@1.0} and @code{@@2.0} and no section had to change its tag.

@example
@@1.0
@@1.1 <-- the newly inserted tag
@@2.0
@@3.0
@@4.0
@end example

If we want to insert anything between @code{@@1.0} and @code{@@1.1} then it could be @code{@@1.01} and a new tag between @code{@@1.1} and @code{@@2.0} could be @code{@@1.2}. Note that a tag can be any number that isn't already taken. Since we are using floating point numbers, we theoretically have infinite possibilities to choose from.

@node Tagline
@section Tagline

The line that tags a section and has the tag number, title of the section, section's references, and section's flags is called tagline. It starts with @code{@@} followed by the tag number, title, references, and flags.

Example of a tagline:
@example
@@1.5 Butterflies _ @@1.2 ^ incomplete
@end example

This line states that the section tag is @code{@@1.5}, followed by the section title "Butterflies", references section @code{@@1.2}, and it has the flag @code{incomplete} which denotes that the section isn't finished yet. The @code{_} (sub) and @code{^} (sup) signs are respectively used for reference lists and flag lists.

@node Tag numbering
@section Tag numbering

Tags are positive alphanumeric floating point numbers made of Latin letters and Arabic numerals that are used to identify and sort sections. Tagstrings are represented with an @code{@@} followed by the tag number. For example, @code{@@1.0}, @code{@@1.19}, @code{@@1.B2}, @code{@@12.5}, and @code{@@786.25} are valid tagstrings. The radix character @code{.} is used to separate the whole number from the fraction.

Floating point number, as explained before, allows inserting infinite number of tags between two pre-existing tags. We can also add tags indefinitely to the beginning and the ending of our document because there's always going to be a floating point number larger than the last tag number and a floating point number smaller than the first tag number.

It should be noted that, @code{@@1.1} is not a child of @code{@@1.0}. @code{@@1.0} is just a number larger than @code{@@1.0}. @code{@@1.0} is same as @code{@@1.0000000...} and @code{@@1.1} is same as @code{@@1.1000000...}.

Alphanumeric means the tag number is made out of both numbers @code{0} through @code{9} and alphabets @code{A} through @code{Z} and @code{a} through @code{z}. After @code{9} comes @code{A}. This is base 62 numeral system. This is chosen so we can express more tags with fewer digits. Furthermore, this allows creating more meaningful tagstrings such as @code{@@LogY2025.M04D15}.

All of the ``numbers'' in base 62 numeral system in ascending order:
@example
0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
@end example

A tag section can have parent tag section and the tagstring will be expressed like @code{@@parent_tag/child_tag}. For example, @code{@@4.5/1.0}; here @code{@@1.0} is section under @code{@@4.5}. @code{@@4.5/1.0} is not the same as @code{1.0}. Both can coexist in the same document.

There a few rules to choosing a tag number. A tag number must be greater than zero. @code{@@0.0} is not a valid tagstring. A tagstring cannot contain anything other than one @code{@@} in the beginning, letters and digits for mantissa, one radix point @code{.} to separate the whole number from the fraction, and @code{/} seperators to create tags under tags. A tag section cannot have a higher tag number than the tag section after it and a tag section cannot have a lower tag number than the tag section before it. If a tag is inserted between two tags, it must be a number between those two tags.

Leading zeros may be ignored but it is adviced against unless it's right before the radic point @code{.}. Multiple radix points in one tagstring is allowed. It can be used for clarity. All the radix points other than the first one will be ignored. Similar to leading zeros, trailing zeros are also discouraged.

A tag number under the hood is implemented with a string mantissa and an integer exponent. This is similar to how floats and doubles are implemented. This custom data type is chosen over float/double for precision and infinite range.

@bye
