\input texinfo
@settitle Tag Manual

@include version.texi

@copying
This manual is for Tag version @value{VERSION}.

Copyright @copyright{} 2025 Sayed Takey Tajwar Arko.

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
Texts.  A copy of the license is included in the section entitled
``GNU Free Documentation License''.
@end quotation
@end copying

@titlepage
@title Tag Manual
@page
@vskip 0pt plus 1filll
@end titlepage

@contents

@node Top
@top The Tag Manual

@insertcopying

@menu
* Introduction::                        Introduction to the core philosophy of Tags

* GNU Free Documentation License::      Copying and sharing this documentation.
@end menu

@node Introduction
@chapter Introduction

Tag is an editor-independent plain text file indexing format that is used to establish connections between multiple files and items. This is done so by referencing one Tag item inside another in a Tag file. Tag files end with the @samp{.tag} extension.

Tag files contain Tag items sorted by their alphanumeric Tag numbers (ID). This makes looking up and referencing items a lot easier than in other document formats.

Tag is designed to be used for organizing your note files, keeping track of your todo lists, simplyfying literate programming, and creating software automation. But, Tag can be used for any place where you need to draw connection between multiple items in a simple plain text format.

Tag is largely inspired by Niklas Luhmann's Zettelkasten method.

@node How Tag Numbering works
@section How Tag Numbering works

If we permanently tag our items with floating point numbers and sort them by their tag number, we'll have a plain text document format that's quick to look up and easy to refer to. For example, let's say we have four items with the tags @samp{@@1.0, @@2.0, @@3.0, @@4.0}:

@example
@@1.0
@@2.0
@@3.0
@@4.0
@end example

@noindent And, we want to insert a new item after @samp{@@1.0} but we don't want to change the tag number of the previous items. What we do here is tag the new item a number between @samp{@@1.0} and @samp{@@2.0} and insert them between those two items. @samp{@@1.1} will suffice here. So, the five sections are @samp{@@1.0, @@1.1, @@2.0, @@3.0, @@4.0} where the new @samp{@@1.1} is between @samp{@@1.0} and @samp{@@2.0}:

@example
@@1.0
@@1.1 <-- the newly inserted item
@@2.0
@@3.0
@@4.0
@end example

@noindent You may have thought we would make the new item the new @samp{@@2.0} and increment the tag number of all the old items from @samp{@@2.0} onwards BUT if we followed such method then the tag numbers wouldn't be permanent. We need permanent identification number so we can reference items by their tag number and rest assure that it never change into another item.

@noindent Note that a tag can be any positive number that isn't already taken. The tag for the new item could have been any number between @samp{1.0} and @samp{2.0} such as @samp{@@1.01}, @samp{@@1.9}, etc. We have infinite possibilities to choose from.

@node Tag items
@section Tag items

The individual elements in a Tag file that are permanently marked with an unique tag number are called tag items. Tag items start at the beginning of line with an @samp{@@} sign followed by its tag number. They can optionally have title, reference list, flag list, and path to its associated file. Example of a tag item:

@example
@@1.5 Butterflies _ @@1.2 ^ incomplete < butterflies.txt
@end example

Here, the tag of the item is @samp{@@1.5}, it has title @samp{Butterflies}, it references another item with tag @samp{@@1.2}, it has the flag @samp{incomplete}, and its contents lie in a file called @file{butterflies.txt}. We can imagine there's a file @file{butterflies.txt} in the same directory as our Tag file.

@node Tag numbers
@section Tag numbers

Tag numbers are positive alphanumeric floating point numbers consisting of Latin letters and/or Arabic numerals that are used to identify and sort tag items. Tag numbers are represented with an @samp{@@} followed by the tag number. For example, @samp{@@1.0}, @samp{@@1.1}, @samp{@@1.19}, @samp{@@1.B2}, @samp{@@12.5}, @samp{@@786.25}, @samp{@@300000000.59}, and @samp{@@0.0000000001} are all valid tag numbers. The radix-point character @samp{.} is used to separate the whole number from the fraction.

@noindent The tag number is alphanumeric which means the tag number is made out of both numbers @samp{0} through @samp{9} and alphabets @samp{A} through @samp{Z} and @samp{a} through @samp{z}. After @samp{9} comes @samp{A}. This is base 62 numeral system. This is chosen so we can express more tags with fewer digits and create more meaningful tag numbers. All of the numbers in base 62 numeral system in ascending order:

@example
0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
@end example

@noindent There a few rules to choosing a tag numbers:

@itemize @bullet{}
@item
A tag number cannot contain anything other than:

@itemize @minus{}
@item
one @samp{@@} in the beginning

@item
alphanumeric characters

@item
radix point @samp{.}

@item
@samp{/} parent-child separator
@end itemize

@item
A tag number must be greater than zero. @samp{@@0.0} is not a valid number.

@item
There cannot be two tag items in one document with the same tag number.

@item
The number must be greater than previous item's and smaller than next item's.
@end itemize

@noindent A tag number under the hood is implemented with a string mantissa and an integer exponent. This custom data type is chosen over float/double for range and precision.

@node Title
@section Title

A section or any other element can be given a title. For sections, the title is one word or multiple words inside curly braces that comes after the tagstring. Example of sections with titles:

@example
@@1.0 Title
@@2.0 @{Longer Title@}
@end example

@noindent A section must not be referenced using its title. The tagstring should be used instead. The title of a section can be used for description and exporting. Elements other than sections, such as files and variables, can be referred using their title.

@node References
@section References

References are important part of the Tag system. Using references we can make connections between two sections. This is useful when you have a section that refers to contents mentioned in another section. Futhermore, referencing allows us to use files and variables from another section and refer to files and variables to reuse them. Reference list comes after the title of a tag element and the underscore symbol @code{_}. If you are referencing only one element then you can write the address (tagstring or title depending on the element type) after the @code{_}. For example:

@example
@@1.0 @{Origin of Butterflies@}
::SOURCE: [[https://pmc.ncbi.nlm.nih.gov/articles/PMC10250192/]]
Butterflies are flying insects from the Lepidoptera
superfamily. Moleculars evidences suggests that
butterflies may have originated in the Cretaceous period.

@@2.0 @{Butterflies in Jurrassic Period?@} _ @@1.0
Butterflies likely originated from the Cretaceous
period, which was 145 to 66 million years ago.
Jurassic period was 201 and 145 million years ago.
So, unless there's new evidence, butterflies probably
didn't exist during the Jurassic period.
@end example

@noindent If you are referencing multiple elements then you'll have to put them inside comma separated curly braces. Example:

@example
@@3.75 World _ @{@@1.2, @@2.8, @@4.5@}
@end example

@noindent You can also refer to sections outside of the current document using either the absolute path or the relative path followed by @code{::} and the tagstring. For example:
@example
@@1.2 @{Why Tagging System@} _ @{./Notes.tag::@@1.0@}
@end example

@node Flags
@section Flags

Flags are words or labels used to convey the quality or features of a Tag element. For example, a section can have the ``ARCHIVED'' flag indicating that the section is now archived (and will be ignored by the compiler). Flag lists starts after the reference list followed by the caret sign @code{^}. If the reference list is absent, flag list can start right after the title. Flags are case sensitive. Here's an example of flag used to convey that a section is still incomplete:

@example
@@3.75 @{Faith and Humanity@} _ @@2.59 ^ incomplete
@end example

@noindent Flags can be used to convey that a section is now archived. For example:

@example
@@5.1 Drilldozer _ @@1.0 ^ ARCHIVED
@end example

@noindent Todo flags can be also used to turn a section into a todo item. ``TODO'' and ``DONE'' are the two basic todo states but more can be used. Examples of sections with todo flags:

@example
@@td.01 @{Finish section: attributes@} ^ TODO
@@td.02 @{Write about biggest overcomes@} ^ DONE
@@td.31 @{Share Tag with others@} ^ @{TODO, IMPORTANT@}
@end example

@noindent Some flags have parameter. For example, "MOVED-TO" flag will need an argument tagstring to indicate its new location. Example of a flag with argument that indicates the new location of the section:

@example
@@1.75 ^ MOVED-TO=@@5.0
@@5.0 Ingenuity
@end example

@noindent Flags aren't just labels you use to tell Tag compiler how you want your element to be treated. Flags can be words you use to describe a tag element. If a flag is foreign to the compiler, it will ignore it.

@node Contents
@section Contents

A section content is the body of the section. Contents may contain paragraphs, comments, metadata, etc. The content of a section starts right after the tagline and ends right before the next section's tagline or EOF. Example of a section with content:

@example
@@1.92 Title
This is the contents of section @@1.92 titled "Title".
@end example

@noindent Contents can have multiple paragraphs. Each paragraph will have to be separated by at least one blankline. For example:

@example
@@0.9A @{Multi-paragraph contents@}

It is possible for a section to have multiple paragraphs.

In that case they can be separated by blanklines.

Blanklines can also be used between taglines for clarity and readability.
@end example

It is possible for sections to not have any content at all. Example of two sections without contents:

@example
@@1.0 First
@@2.0 Second
@end example

@node Metadata
@section Metadata

Metadata are data about data. Metadata are useful when you need to provide information regarding certain data and how they should be processed. In Tag, metadata are used to tell the compiler how to process the data and provide context for human readers. Metadata resides in the content of a section and uses @code{::KEY:VALUE} format. Metadata can be used to indicate creation and modification time. For example:

@example
@@1.1 @{Section with creation time@}
::BIRTH: [2025-04-21T02:18:17+06:00]
::MODIFIED: [2025-04-21T21:44:52+06:00]
This section was created on 21st April 2025 at 2:18 and was
last modified on 21st April 2025 at 21:44 (UTC+06:00).
@end example

@noindent Metadata can be used to schedule a task. For example:

@example
@@9.47 @{Watch Le Trou (1960)@} ^ TODO
::SCHEDULED: <2025-06-01T18:00/PT2H20M>
@end example

@noindent Metadata entries that are situated at the beginning of the document and not part of any section are document metadata. They can tell the compiler how to process the whole document and also the viewer information about the whole documents. For example, metadata used to provide descriptive information:

@example
::TITLE: Metadata is amazing!
::AUTHOR: One who loves metadata
@@1.0 @{What is metadata@}
@@2.0 @{Why we need metadata@} ^ @@1.0
@end example

@noindent For some metadata a single line isn't enough. For such, we need metadata drawer. A metadata drawer is essentially a metadata set or schema. A metadata drawer starts with @code{:::DRAWER-NAME} and ends with @code{:::DRAWER-NAME}. Example of drawer used to keep log of all the changes of a section:

@example
@@4.7g2 @{Frequently changing section@}
:::LOGS
::MODIFIED: [2025-04-21T12:10:23Z]
::MODIFIED: [2025-04-21T12:05:47Z]
::MODIFIED: [2025-04-21T12:00:32Z]
::BIRTH: [2025-04-21T12:00:00Z]
:::LOGS
I last updated this section on 21st April 2025 at 12:10:23!
@end example

@noindent Drawers can used to keep a reference list. For example:

@example
@@2.15t @{Referencing is important!@} ^ markup

It is very important to reference what you cite. So, it is *important
to keep a list of all the references so you don't forget*.
Let's imagine that in this section we are citing the work of two imaginary
people Ivanka Ivanwich and Josephine Vargas. Ivanwish (1998) argues that
referencing is important for solely legality but Vargas (2003) points out
that there are other reasons referencing is important.

:::REFERENCES
Ivanka, I. (1998). /Laws and Library/. Damir Publishing.
Vargas, J. (2003). /Art of Academia/. Alba Arts.
:::REFERENCES
@end example

@noindent Feel free to make your own metadata for clarity and extension. A metadata key that is foreign to the compiler will be ignored.

@node Comments
@section Comments

Comments in Tag are special kind of metadata that can be used for annotation. A single line can be commented using the @code{::COMMENT:} key. For example:

@example
@@3.63 @{Provoking Thoughts@}
People of different philosophies have different ideas
on the origin of our thoughts and consciousness.
::COMMENT: Thoughts as a form of psychic energy
Thoughts in spirituality are believed to arise
from energy and vibration. Many spiritualists
also believe karma to be a by-product of thoughts.
@end example

@noindent A multi line comment can reside inside the @code{:::COMMENTS} drawer. For example:

@example
@@2.33 @{A lot to say@}
:::COMMENTS
Sometimes we have a lot to say about something
that may not fit in one line. In that case,
we can use the :::COMMENTS drawer.
:::COMMENTS
@end example

@noindent If you want your comments to be more cautionary then you can use warnings instead. Warnings are statements that warns the reader. They can can be done with @code{::WARNING:} metadata. For example:

@example
@@8.95 @{Liquid Methane and Hot Lava Demonstration@}
Let's find out what happens when hot lava meets liquid nitrogen.
::WARNING: DON'T TRY THIS AT HOME
We'll need rocks and enough heat to melt
them, liquid methane, and proper lab equipments.
@end example

@noindent Or, with the @code{:::WARNINGS} drawer. For example:

@example
@@3.423 @{Commenting taglines?@}
:::WARNINGS
Avoid putting taglines inside comments.
The behavior for doing so is undefined.
If you must, add a blank space at the
beginning of the commented tagline.
:::WARNING
@end example

@node Markup
@section Markup

Tag supports markup for rich formatting. Markup allows you to indicate how your plain text document should be displayed and exported. To enable markup in a section, you will need to add @code{MARKUP} flag in that section. Once enabled, you'll need to surround the block of text you'd like to be marked up in special symbols. For example, to emphasis your text:

@example
@@10.37 @{Text Emphasis@} ^ MARKUP
You can *bold*, /italicize/, _underline_,
+strike-through+, #highlight#, and ~code~ your text.
The special symbols will have to surround your
desired text and not be inbetween alphanumeric symbols.
@end example

@noindent You can also insert links in your document by surrounding them inside square brackets. For example:

@example
@@10.38 @{Links and URLs@} ^ MARKUP
You can insert a link like [[https://example.com]].
If you'd like to provide description with your
link, you can use [[Link][Description]] format
like [[https://example.com][Example site]].
You can also link other files, using aboslute
or relative path, like [[./file.tag]].
@end example

@noindent You can also add inline math with @code{$} symbol. You'll need to use the @code{TeX} flag for this one to work. For example:

@example
@@10.57 @{Inline Math@} ^ TeX
$(x+y)^2 = x^2 + 2xy + y^2$
@end example

You might need to install a TeX engine for this to work.

@noindent Tag's markup language was mostly inspired by Org mode's. However, Tag supports some markups that Org doesn't and doesn't provide support for verbatim monospacing as it's unnecessary when there's code present.

@node GNU Free Documentation License
@appendix GNU Free Documentation License

@include fdl-1.3.texi

@bye
